blank_issues_enabled: true
contact_links:
  - name: I just have a question...
    url: https://github.com/NatLabRockies/thevenin/discussions
    about: Join our discussion instead. Search for existing questions, or ask a new one!